#!/bin/bash -e
set -x

if [ "$#" != 1 ]; then
    echo "Usage: ./run <kernel-version/gdb>"
    echo "      e.g., ./run kernel1"
    exit 0
fi

kernel=$1

if [ "$1" == "gdb" ]; then
    kernel=kernel1
    upper=`echo kernel1 | tr '[:lower:]' '[:upper:]'`
else
    upper=`echo $1 | tr '[:lower:]' '[:upper:]'`
fi

make clean
./generate-measurements
make all
cp kernel/kernel kernel1
./create-recovery $kernel

if [ "$1" == "gdb" ]; then
    echo ""
    echo "Executing $kernel with GDB.. "
    make qemu-gdb
else 
    echo ""
    echo "Executing $kernel.. "
    make qemu
fi
